### ISSUE TITLE
How is it supposed to work ?

### ISSUE THREAD

**Issue by naholyr** [wearefractal/spex#1]
The "examples" link in documentation is broken.
No binary is provided.

No way to guess how this module is supposedly used :(

**Comment by yocontra** [comment]
It isn't finished yet. Check back in a day or two

**Comment by naholyr** [comment]
You may not publish it on npm then ;) I thought every published module was at least runnable :P

**Comment by vitaly-t** [comment]
that's how all good names get squatted. I wanted to use the name, but I see it just being wasted now.
