### ISSUE TITLE
NPM Name Release

### ISSUE THREAD

**Issue by vitaly-t** [wearefractal/spex#2]
A formal request has been submitted to [contact@wearefractal.com](mailto:contact@wearefractal.com) and NPM support to release "spex" name on NPM, after being occupied by and large non-functioning and unsupported library for 4 years, which qualifies, as per NPM terms of fair usage, being squatted.

I'm also using the following post as a reference: #1

**Comment by yocontra** [comment]
Yes, this is already done. Stop.

**Comment by vitaly-t** [comment]
Cheers!

Just so, there is `spex-cli` package published, with dependency on the now removed `spex` ;)
